sudo: false
language: go
go:
  - 1.8.x
install:
  - nvm install node
  - npm install -g source-map-support
  - go get -u github.com/gopherjs/gopherjs
  - go get -u github.com/golang/lint/golint
  - go get -u honnef.co/go/tools/cmd/megacheck
  - go get -u github.com/haya14busa/goverage
before_script:
  - export NODE_PATH="/usr/local/lib/node_modules"
script:
  # Fetch dependencies.
  - go get -t -v ./...

  # Consult Go fmt, vet, lint, megacheck tools.
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .
  - golint -set_exit_status . ./examples/...
  - golint ./elem/... event/... prop/... storeutil/... # TODO(slimsag): address these linter errors
  - megacheck ./...
  - megacheck -tags=js ./...

  # Test with Go compiler and GopherJS compiler.
  - go test -v -race ./...
  - gopherjs test -v $(go list ./...)

  # Generate and upload coverage to codecov.io
  - goverage -covermode=atomic -coverprofile=coverage.out $(go list ./... | grep -v -e vecty/elem -e vecty/event -e vecty/examples -e vecty/prop -e vecty/style)
  - include_cov=coverage.out bash <(curl -s https://codecov.io/bash)
